### ISSUE TITLE
Sign in is not working

### ISSUE THREAD

**Issue by chatii** [integrations/slack#1941]
**Describe the bug**
When attempting to sign in, the process does not complete as expected. I tried using the `/github subscribe org/repo` command but received the following message:

> Request taking too long to process, still processing

ref: #1940  

I also tried retrying with /github signin, but the sign-in still does not work.

**To Reproduce**
1. `/github signin`
2. In the opened browser, click on "Connect GitHub Account."
3. "Service Unavailable" on `https://slack.github.com/github/v2/oauth/callback?browser_session_id=xxxxxxx&code=xxxxxxxx`

**Expected behavior**

**Screenshots**
<img width="453" alt="スクリーンショット 2024-09-04 23 49 37" src="https://github.com/user-attachments/assets/ba7bfa9a-5b97-4fa9-a71e-13a20dcf96b0">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome (and Slack Desktop app)
 - Version 128.0.6613.86（Official Build） （arm64）

**Comment by chatii** [comment]
There is already an issue regarding the subscribe command not working, but since I am not sure if the cause is the same, I created a separate issue. I do not intend to post multiple times on the same topic.

**Comment by gr2m** [comment]
this issue should be resolved now, sorry for the trouble. We are working on some major changes which will likely cause more friction unfortunately, but it will set the foundation for the chat integrations moving forward.

Can you confirm it's working now for you?

**Comment by chatii** [comment]
@gr2m 

Yes, I just tried it, and the login screen progressed normally, displaying the Verification Code. When I entered the Code on Slack, it seems that I was able to log in successfully! THX!!

**Comment by ibrahim-mubarak** [comment]
Hi
I'm still facing this issue

Service unavailable on 
https://slack.github.com/github/v2/oauth/callback?browser_session_id=xxxxx&state=xxxxx

**Comment by mario-steinhoff-gcx** [comment]
> We are working on some major changes which will likely cause more friction unfortunately, but it will set the foundation for the chat integrations moving forward.

@gr2m Sorry for hijacking this issue but since a few days we are "sometimes" not receiving slack messages for issues, pull requests, and comments anymore. I really hope that this will not end up in a situation like we had with #1500.

**Comment by ovofoxy** [comment]
I'm still getting the "Service Unavailable" message when trying to login
